# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
#  - name: Papers
#    url: /#papers
#    weight: 11
#  - name: News
#    url: /post/
#    weight: 13
  - name: Research
    url: /research/
    weight: 15
  - name: Education and Experience
    url: education_and_experience/
    weight: 20
  - name: Teaching and Outreach
    url: teaching_and_outreach/
    weight: 30
  - name: Design Portfolio
    url: design_portfolio/
    weight: 40
